name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "f4994730-2049-4d3f-8618-57302c9784db"      # 替换为你创建的数据库 ID
